### ISSUE TITLE
Feature Name is Undefined

### ISSUE THREAD

**Issue by agroppi** [cmdcolin/region_retriever#1]
In the README.md  : 
```
column 5 - feature id
column 5 - feature name
```
Shouldn't it be  column **6** ?

Actually the ouput file has only 5 columns

In this 5th column for some track label the feature extracted is always "Undefined"

And for some other track labels the extracted feature is not the name but the characteristics for example : 
"ORF type:complete len:674 (+),score=94.21" instead of "jg25977.t1.p1"

I not very familiar with js but I thinks that the problem could be due to the column 5/ 6 "bug"

Tell me if you need some files to test this.

Thanks again

**Comment by cmdcolin** [comment]
@agroppi that stems from a little confusion on my own part, currently column 5 is whatever is in Name= in the original GFF, which people sometimes put a lot of accessory information in

It does not currently output ID because I had some trouble with that hence the confusion with the readme. There is no column 6 currently. I can try and update it so that it outputs ID= also and maybe outputs just a dot ('.') instead of undefined if that is easier to understand than the undefined values

**Comment by agroppi** [comment]
@cmdcolin 
more details  with an example :  region = chr1:970303..972918
on this screenshot : 
![region_retriever_1](https://user-images.githubusercontent.com/5609985/61963153-4f969000-afcb-11e9-9c44-445fc46eb7ba.JPG)

But on the result given by region_retriever : 

REPET_TEs_Elements | chr1 | 970966 | 971026 | undefined
```
REPET_TEs_Elements | chr1 | 971026 | 976239 | undefined
Braker2_mRNA_Prediction | chr1 | 971056 | 972217 | ORF type:complete len:387 (+),score=71.65
BlastX_prediction_hits_Plant | chr1 | 971107 | 972196 | undefined
BlastP_prediction_hits_Plant | chr1 | 971107 | 971470 | undefined
pfam_domains_braker_predictions | chr1 | 971587 | 971789 | PF00931.NB-ARC.NB-ARC_domain
Trinity_FM14_mRNA_Assembly | chr1 | 971707 | 972079 | TRINITY_GG_3963_c0_g1_i1.p1
REPET_TEs_Elements | chr1 | 972789 | 972904 | undefined
REPET_TEs_Elements | chr1 | 972986 | 973152 | undefined
```
For example for the BlastX track the the hits BlastX are set as "undefined" by region_retriever.

**Comment by cmdcolin** [comment]
@agroppi I would imagine the original GFF for those tracks didn't contain a Name= column in column 9 of the GFF (which is perfectly legal). In this case, I would just ignore the fact that this column is undefined.

In order to retrieve the ID we will fix this bug in nclist-js https://github.com/GMOD/nclist-js/issues/2 and then I can keep you posted

Note: the displayed black feature label is basically evaluated by the javascript expression

feature.get('name') || feature.get('id')

E.g. it displays the ID= from GFF column 9 if the Name= is undefined

**Comment by cmdcolin** [comment]
Alright turns out it wasn't a bug in nclist but I fixed it in this script

Feel free to retry

I now have it output a dot ('.') if the ID or Name is undefined and it does six column output

**Comment by cmdcolin** [comment]
Should be fixed, if another issue feel free to repost

**Comment by agroppi** [comment]
Dear @cmdcolin 
It works like a charm.
Thank you :)
